import { defineConfig } from 'vitepress'
export default defineConfig({
  title: "ヰ世界製歌",
  description: "isekaiuta",
  themeConfig: {
    logo: '/favicon.ico',
    nav: [
      { text: 'ヰ世界製菓', link: 'https://z46.icu/' },
    ],
    sidebar: [
      { text: 'ガールズバンドクライ', collapsed: false, items: [
        { text: "空の箱", link: '/ガールズバンドクライ/空の箱' },
        { text: "雑踏、僕らの街", link: '/ガールズバンドクライ/雑踏、僕らの街' },      ],
      },
      { text: 'ユルーカ研究所', collapsed: false, items: [
        { text: "魔法のない世界で生きるということ", link: '/ユルーカ研究所/魔法のない世界で生きるということ' },      ],
      },
      { text: 'ヰ世界情緒', collapsed: false, items: [
        { text: "キミ消失セカイ", link: '/ヰ世界情緒/キミ消失セカイ' },
        { text: "シリウスの心臓", link: '/ヰ世界情緒/シリウスの心臓' },
        { text: "パンドラコール", link: '/ヰ世界情緒/パンドラコール' },
        { text: "ヰ世界の宝石譚", link: '/ヰ世界情緒/ヰ世界の宝石譚' },
        { text: "暮れなずむ約束", link: '/ヰ世界情緒/暮れなずむ約束' },
        { text: "物語りのワルツ", link: '/ヰ世界情緒/物語りのワルツ' },
        { text: "霞がついてくる", link: '/ヰ世界情緒/霞がついてくる' },      ],
      },
      { text: 'ヰ世界情緒（歌てみった）', collapsed: false, items: [
        { text: "Chaining Intention", link: '/ヰ世界情緒（歌てみった）/Chaining Intention' },
        { text: "Fairytale,", link: '/ヰ世界情緒（歌てみった）/Fairytale,' },
        { text: "INTERNET YAMERO feat. KOTOKO", link: '/ヰ世界情緒（歌てみった）/INTERNET YAMERO feat. KOTOKO' },
        { text: "Loveit feat. LOLUET", link: '/ヰ世界情緒（歌てみった）/Loveit feat. LOLUET' },
        { text: "Who", link: '/ヰ世界情緒（歌てみった）/Who' },
        { text: "flos", link: '/ヰ世界情緒（歌てみった）/flos' },
        { text: "morning haze", link: '/ヰ世界情緒（歌てみった）/morning haze' },
        { text: "paranoia", link: '/ヰ世界情緒（歌てみった）/paranoia' },
        { text: "why,or why not", link: '/ヰ世界情緒（歌てみった）/why,or why not' },
        { text: "あだぽしゃ", link: '/ヰ世界情緒（歌てみった）/あだぽしゃ' },
        { text: "あなぐらぐらし", link: '/ヰ世界情緒（歌てみった）/あなぐらぐらし' },
        { text: "いのちの名前", link: '/ヰ世界情緒（歌てみった）/いのちの名前' },
        { text: "お呪い", link: '/ヰ世界情緒（歌てみった）/お呪い' },
        { text: "ねがい", link: '/ヰ世界情緒（歌てみった）/ねがい' },
        { text: "アリス", link: '/ヰ世界情緒（歌てみった）/アリス' },
        { text: "アンノウン・マザーグース", link: '/ヰ世界情緒（歌てみった）/アンノウン・マザーグース' },
        { text: "エンドロール", link: '/ヰ世界情緒（歌てみった）/エンドロール' },
        { text: "カミノコトバ", link: '/ヰ世界情緒（歌てみった）/カミノコトバ' },
        { text: "ギャラリア", link: '/ヰ世界情緒（歌てみった）/ギャラリア' },
        { text: "スイートマジック", link: '/ヰ世界情緒（歌てみった）/スイートマジック' },
        { text: "パノプティコン", link: '/ヰ世界情緒（歌てみった）/パノプティコン' },
        { text: "ブラック★ロックシューター", link: '/ヰ世界情緒（歌てみった）/ブラック★ロックシューター' },
        { text: "プラチナ", link: '/ヰ世界情緒（歌てみった）/プラチナ' },
        { text: "ペイメント", link: '/ヰ世界情緒（歌てみった）/ペイメント' },
        { text: "マカロン", link: '/ヰ世界情緒（歌てみった）/マカロン' },
        { text: "メテオ", link: '/ヰ世界情緒（歌てみった）/メテオ' },
        { text: "メリクリ", link: '/ヰ世界情緒（歌てみった）/メリクリ' },
        { text: "レイニーブーツ", link: '/ヰ世界情緒（歌てみった）/レイニーブーツ' },
        { text: "レプリカ", link: '/ヰ世界情緒（歌てみった）/レプリカ' },
        { text: "ロスト・デリュージョン", link: '/ヰ世界情緒（歌てみった）/ロスト・デリュージョン' },
        { text: "人マニア", link: '/ヰ世界情緒（歌てみった）/人マニア' },
        { text: "僕らの記憶を掠わないで", link: '/ヰ世界情緒（歌てみった）/僕らの記憶を掠わないで' },
        { text: "共感覚おばけ", link: '/ヰ世界情緒（歌てみった）/共感覚おばけ' },
        { text: "初恋日記", link: '/ヰ世界情緒（歌てみった）/初恋日記' },
        { text: "君が生きてなくてよかった", link: '/ヰ世界情緒（歌てみった）/君が生きてなくてよかった' },
        { text: "垂直落下", link: '/ヰ世界情緒（歌てみった）/垂直落下' },
        { text: "変わらないもの", link: '/ヰ世界情緒（歌てみった）/変わらないもの' },
        { text: "夜顔の告白", link: '/ヰ世界情緒（歌てみった）/夜顔の告白' },
        { text: "少女レイ", link: '/ヰ世界情緒（歌てみった）/少女レイ' },
        { text: "撫でんな", link: '/ヰ世界情緒（歌てみった）/撫でんな' },
        { text: "旅の途中", link: '/ヰ世界情緒（歌てみった）/旅の途中' },
        { text: "春はゆく", link: '/ヰ世界情緒（歌てみった）/春はゆく' },
        { text: "桜流し", link: '/ヰ世界情緒（歌てみった）/桜流し' },
        { text: "死ぬのがいいわ", link: '/ヰ世界情緒（歌てみった）/死ぬのがいいわ' },
        { text: "海の幽霊", link: '/ヰ世界情緒（歌てみった）/海の幽霊' },
        { text: "熱愛発覚中", link: '/ヰ世界情緒（歌てみった）/熱愛発覚中' },
        { text: "熱異常", link: '/ヰ世界情緒（歌てみった）/熱異常' },
        { text: "猫の食卓", link: '/ヰ世界情緒（歌てみった）/猫の食卓' },
        { text: "白昼夢", link: '/ヰ世界情緒（歌てみった）/白昼夢' },
        { text: "第三の心臓", link: '/ヰ世界情緒（歌てみった）/第三の心臓' },
        { text: "約束", link: '/ヰ世界情緒（歌てみった）/約束' },
        { text: "誰か、海を。", link: '/ヰ世界情緒（歌てみった）/誰か、海を。' },
        { text: "運命", link: '/ヰ世界情緒（歌てみった）/運命' },
        { text: "鳳仙花", link: '/ヰ世界情緒（歌てみった）/鳳仙花' },      ],
      },
      { text: '星街すいせい', collapsed: false, items: [
        { text: "ビビデバ", link: '/星街すいせい/ビビデバ' },      ],
      },
      { text: '花譜', collapsed: false, items: [
        { text: "それを世界と言うんだね", link: '/花譜/それを世界と言うんだね' },      ],
      },

  ],
    socialLinks: [
      { icon: 'twitter', link: 'https://github.com/vuejs/vitepress' },
    ],
    search: {
      provider: 'local',
    },
  },
})
