import { defineConfig } from 'vitepress'
export default defineConfig({
  title: "ヰ世界製歌",
  description: "isekaiuta",
  themeConfig: {
    logo: '/favicon.ico',
    nav: [
      { text: 'ヰ世界製菓', link: 'https://z46.icu/' },
    ],
    sidebar: [
      { text: 'ガールズバンドクライ', items: [
        { text: "空の箱", link: '/ガールズバンドクライ/空の箱' },
        { text: "雑踏、僕らの街", link: '/ガールズバンドクライ/雑踏、僕らの街' },      ],
      },
      { text: 'ヰ世界情緒', items: [
        { text: "Chaining Intention", link: '/ヰ世界情緒/Chaining Intention' },
        { text: "Fairytale,", link: '/ヰ世界情緒/Fairytale,' },
        { text: "INTERNET YAMERO feat. KOTOKO", link: '/ヰ世界情緒/INTERNET YAMERO feat. KOTOKO' },
        { text: "Loveit feat. LOLUET", link: '/ヰ世界情緒/Loveit feat. LOLUET' },
        { text: "Who", link: '/ヰ世界情緒/Who' },
        { text: "flos", link: '/ヰ世界情緒/flos' },
        { text: "morning haze", link: '/ヰ世界情緒/morning haze' },
        { text: "paranoia", link: '/ヰ世界情緒/paranoia' },
        { text: "why,or why not", link: '/ヰ世界情緒/why,or why not' },
        { text: "あだぽしゃ", link: '/ヰ世界情緒/あだぽしゃ' },
        { text: "あなぐらぐらし", link: '/ヰ世界情緒/あなぐらぐらし' },
        { text: "いのちの名前", link: '/ヰ世界情緒/いのちの名前' },
        { text: "お呪い", link: '/ヰ世界情緒/お呪い' },
        { text: "ねがい", link: '/ヰ世界情緒/ねがい' },
        { text: "アリス", link: '/ヰ世界情緒/アリス' },
        { text: "アンノウン・マザーグース", link: '/ヰ世界情緒/アンノウン・マザーグース' },
        { text: "エンドロール", link: '/ヰ世界情緒/エンドロール' },
        { text: "カミノコトバ", link: '/ヰ世界情緒/カミノコトバ' },
        { text: "ギャラリア", link: '/ヰ世界情緒/ギャラリア' },
        { text: "スイートマジック", link: '/ヰ世界情緒/スイートマジック' },
        { text: "パノプティコン", link: '/ヰ世界情緒/パノプティコン' },
        { text: "ブラック★ロックシューター", link: '/ヰ世界情緒/ブラック★ロックシューター' },
        { text: "プラチナ", link: '/ヰ世界情緒/プラチナ' },
        { text: "ペイメント", link: '/ヰ世界情緒/ペイメント' },
        { text: "マカロン", link: '/ヰ世界情緒/マカロン' },
        { text: "メテオ", link: '/ヰ世界情緒/メテオ' },
        { text: "メリクリ", link: '/ヰ世界情緒/メリクリ' },
        { text: "レイニーブーツ", link: '/ヰ世界情緒/レイニーブーツ' },
        { text: "レプリカ", link: '/ヰ世界情緒/レプリカ' },
        { text: "ロスト・デリュージョン", link: '/ヰ世界情緒/ロスト・デリュージョン' },
        { text: "人マニア", link: '/ヰ世界情緒/人マニア' },
        { text: "僕らの記憶を掠わないで", link: '/ヰ世界情緒/僕らの記憶を掠わないで' },
        { text: "共感覚おばけ", link: '/ヰ世界情緒/共感覚おばけ' },
        { text: "初恋日記", link: '/ヰ世界情緒/初恋日記' },
        { text: "君が生きてなくてよかった", link: '/ヰ世界情緒/君が生きてなくてよかった' },
        { text: "垂直落下", link: '/ヰ世界情緒/垂直落下' },
        { text: "変わらないもの", link: '/ヰ世界情緒/変わらないもの' },
        { text: "夜顔の告白", link: '/ヰ世界情緒/夜顔の告白' },
        { text: "少女レイ", link: '/ヰ世界情緒/少女レイ' },
        { text: "撫でんな", link: '/ヰ世界情緒/撫でんな' },
        { text: "旅の途中", link: '/ヰ世界情緒/旅の途中' },
        { text: "春はゆく", link: '/ヰ世界情緒/春はゆく' },
        { text: "桜流し", link: '/ヰ世界情緒/桜流し' },
        { text: "死ぬのがいいわ", link: '/ヰ世界情緒/死ぬのがいいわ' },
        { text: "海の幽霊", link: '/ヰ世界情緒/海の幽霊' },
        { text: "熱愛発覚中", link: '/ヰ世界情緒/熱愛発覚中' },
        { text: "熱異常", link: '/ヰ世界情緒/熱異常' },
        { text: "猫の食卓", link: '/ヰ世界情緒/猫の食卓' },
        { text: "白昼夢", link: '/ヰ世界情緒/白昼夢' },
        { text: "第三の心臓", link: '/ヰ世界情緒/第三の心臓' },
        { text: "約束", link: '/ヰ世界情緒/約束' },
        { text: "誰か、海を。", link: '/ヰ世界情緒/誰か、海を。' },
        { text: "運命", link: '/ヰ世界情緒/運命' },
        { text: "鳳仙花", link: '/ヰ世界情緒/鳳仙花' },      ],
      },

  ],
    socialLinks: [
      { icon: 'twitter', link: 'https://github.com/vuejs/vitepress' },
    ],
    search: {
      provider: 'local',
    },
  },
})
