import { defineConfig } from 'vitepress'
export default defineConfig({
  title: "ヰ世界製歌",
  description: "isekaiuta",
  themeConfig: {
    logo: '/favicon.ico',
    nav: [
      { text: 'ヰ世界製菓', link: 'https://z46.icu/' },
    ],
    sidebar: [
      { text: '25時、ナイトコードで。', collapsed: false, items: [
        { text: "Iなんです", link: '/25時、ナイトコードで。/Iなんです' },
        { text: "それがあなたの幸せとしても", link: '/25時、ナイトコードで。/それがあなたの幸せとしても' },
        { text: "アイディスマイル", link: '/25時、ナイトコードで。/アイディスマイル' },
        { text: "カトラリー", link: '/25時、ナイトコードで。/カトラリー' },
        { text: "カナデトモスソラ", link: '/25時、ナイトコードで。/カナデトモスソラ' },
        { text: "ザムザ", link: '/25時、ナイトコードで。/ザムザ' },
        { text: "シャルル", link: '/25時、ナイトコードで。/シャルル' },
        { text: "ジェヘナ", link: '/25時、ナイトコードで。/ジェヘナ' },
        { text: "トリコロージュ", link: '/25時、ナイトコードで。/トリコロージュ' },
        { text: "ノマド", link: '/25時、ナイトコードで。/ノマド' },
        { text: "ノンブレス・オブリージュ", link: '/25時、ナイトコードで。/ノンブレス・オブリージュ' },
        { text: "ベノム", link: '/25時、ナイトコードで。/ベノム' },
        { text: "ボッカデラベリタ", link: '/25時、ナイトコードで。/ボッカデラベリタ' },
        { text: "メリュー", link: '/25時、ナイトコードで。/メリュー' },
        { text: "再生", link: '/25時、ナイトコードで。/再生' },
        { text: "君の夜をくれ", link: '/25時、ナイトコードで。/君の夜をくれ' },
        { text: "命に嫌われている", link: '/25時、ナイトコードで。/命に嫌われている' },
        { text: "悔やむと書いてミライ", link: '/25時、ナイトコードで。/悔やむと書いてミライ' },
        { text: "泥中に咲く", link: '/25時、ナイトコードで。/泥中に咲く' },
        { text: "独りんぼエンヴィー", link: '/25時、ナイトコードで。/独りんぼエンヴィー' },
        { text: "自傷無色", link: '/25時、ナイトコードで。/自傷無色' },
        { text: "限りなく灰色へ", link: '/25時、ナイトコードで。/限りなく灰色へ' },      ],
      },
      { text: 'CIEL', collapsed: false, items: [
        { text: "君の望み、君の願い", link: '/CIEL/君の望み、君の願い' },
        { text: "少年漫画", link: '/CIEL/少年漫画' },
        { text: "窓を開けて", link: '/CIEL/窓を開けて' },      ],
      },
      { text: 'MyGO!!!!!', collapsed: false, items: [
        { text: "処救生", link: '/MyGO!!!!!/処救生' },
        { text: "名無声", link: '/MyGO!!!!!/名無声' },
        { text: "回層浮", link: '/MyGO!!!!!/回層浮' },
        { text: "影色舞", link: '/MyGO!!!!!/影色舞' },
        { text: "春日影 (MyGO!!!!! ver.)", link: '/MyGO!!!!!/春日影 (MyGO!!!!! ver.)' },
        { text: "栞", link: '/MyGO!!!!!/栞' },
        { text: "歌いましょう鳴らしましょう", link: '/MyGO!!!!!/歌いましょう鳴らしましょう' },
        { text: "潜在表明", link: '/MyGO!!!!!/潜在表明' },
        { text: "焚音打", link: '/MyGO!!!!!/焚音打' },
        { text: "砂寸奏", link: '/MyGO!!!!!/砂寸奏' },
        { text: "迷星叫", link: '/MyGO!!!!!/迷星叫' },
        { text: "音一会", link: '/MyGO!!!!!/音一会' },      ],
      },
      { text: 'V.W.P', collapsed: false, items: [
        { text: "共鳴", link: '/V.W.P/共鳴' },
        { text: "再会", link: '/V.W.P/再会' },
        { text: "分裂", link: '/V.W.P/分裂' },
        { text: "同盟", link: '/V.W.P/同盟' },
        { text: "天命", link: '/V.W.P/天命' },
        { text: "強気", link: '/V.W.P/強気' },
        { text: "明日", link: '/V.W.P/明日' },
        { text: "暁光", link: '/V.W.P/暁光' },
        { text: "未遂", link: '/V.W.P/未遂' },
        { text: "欲望", link: '/V.W.P/欲望' },
        { text: "花束", link: '/V.W.P/花束' },
        { text: "言霊", link: '/V.W.P/言霊' },
        { text: "輪廻", link: '/V.W.P/輪廻' },
        { text: "遊戯", link: '/V.W.P/遊戯' },
        { text: "魔女(真)", link: '/V.W.P/魔女(真)' },      ],
      },
      { text: 'ガールズバンドクライ', collapsed: false, items: [
        { text: "空の箱", link: '/ガールズバンドクライ/空の箱' },
        { text: "雑踏、僕らの街", link: '/ガールズバンドクライ/雑踏、僕らの街' },      ],
      },
      { text: 'ユルーカ研究所', collapsed: false, items: [
        { text: "魔法のない世界で生きるということ", link: '/ユルーカ研究所/魔法のない世界で生きるということ' },      ],
      },
      { text: 'ヰ世界情緒', collapsed: false, items: [
        { text: "Chaining Intention", link: '/ヰ世界情緒/Chaining Intention' },
        { text: "Fairytale,", link: '/ヰ世界情緒/Fairytale,' },
        { text: "INTERNET YAMERO feat. KOTOKO", link: '/ヰ世界情緒/INTERNET YAMERO feat. KOTOKO' },
        { text: "Loveit feat. LOLUET", link: '/ヰ世界情緒/Loveit feat. LOLUET' },
        { text: "Who", link: '/ヰ世界情緒/Who' },
        { text: "flos", link: '/ヰ世界情緒/flos' },
        { text: "morning haze", link: '/ヰ世界情緒/morning haze' },
        { text: "paranoia", link: '/ヰ世界情緒/paranoia' },
        { text: "why,or why not", link: '/ヰ世界情緒/why,or why not' },
        { text: "あだぽしゃ", link: '/ヰ世界情緒/あだぽしゃ' },
        { text: "あなぐらぐらし", link: '/ヰ世界情緒/あなぐらぐらし' },
        { text: "いのちの名前", link: '/ヰ世界情緒/いのちの名前' },
        { text: "お呪い", link: '/ヰ世界情緒/お呪い' },
        { text: "ねがい", link: '/ヰ世界情緒/ねがい' },
        { text: "アリス", link: '/ヰ世界情緒/アリス' },
        { text: "アンノウン・マザーグース", link: '/ヰ世界情緒/アンノウン・マザーグース' },
        { text: "エンドロール", link: '/ヰ世界情緒/エンドロール' },
        { text: "カミノコトバ", link: '/ヰ世界情緒/カミノコトバ' },
        { text: "キミ消失セカイ", link: '/ヰ世界情緒/キミ消失セカイ' },
        { text: "ギャラリア", link: '/ヰ世界情緒/ギャラリア' },
        { text: "シリウスの心臓", link: '/ヰ世界情緒/シリウスの心臓' },
        { text: "スイートマジック", link: '/ヰ世界情緒/スイートマジック' },
        { text: "パノプティコン", link: '/ヰ世界情緒/パノプティコン' },
        { text: "パンドラコール", link: '/ヰ世界情緒/パンドラコール' },
        { text: "ブラック★ロックシューター", link: '/ヰ世界情緒/ブラック★ロックシューター' },
        { text: "プラチナ", link: '/ヰ世界情緒/プラチナ' },
        { text: "ペイメント", link: '/ヰ世界情緒/ペイメント' },
        { text: "マカロン", link: '/ヰ世界情緒/マカロン' },
        { text: "メテオ", link: '/ヰ世界情緒/メテオ' },
        { text: "メリクリ", link: '/ヰ世界情緒/メリクリ' },
        { text: "レイニーブーツ", link: '/ヰ世界情緒/レイニーブーツ' },
        { text: "レプリカ", link: '/ヰ世界情緒/レプリカ' },
        { text: "ロスト・デリュージョン", link: '/ヰ世界情緒/ロスト・デリュージョン' },
        { text: "ヰ世界の宝石譚", link: '/ヰ世界情緒/ヰ世界の宝石譚' },
        { text: "人マニア", link: '/ヰ世界情緒/人マニア' },
        { text: "僕らの記憶を掠わないで", link: '/ヰ世界情緒/僕らの記憶を掠わないで' },
        { text: "共感覚おばけ", link: '/ヰ世界情緒/共感覚おばけ' },
        { text: "初恋日記", link: '/ヰ世界情緒/初恋日記' },
        { text: "君が生きてなくてよかった", link: '/ヰ世界情緒/君が生きてなくてよかった' },
        { text: "垂直落下", link: '/ヰ世界情緒/垂直落下' },
        { text: "変わらないもの", link: '/ヰ世界情緒/変わらないもの' },
        { text: "夜顔の告白", link: '/ヰ世界情緒/夜顔の告白' },
        { text: "少女レイ", link: '/ヰ世界情緒/少女レイ' },
        { text: "撫でんな", link: '/ヰ世界情緒/撫でんな' },
        { text: "旅の途中", link: '/ヰ世界情緒/旅の途中' },
        { text: "星界ちゃんと可不ちゃんのおつかい合騒曲", link: '/ヰ世界情緒/星界ちゃんと可不ちゃんのおつかい合騒曲' },
        { text: "春はゆく", link: '/ヰ世界情緒/春はゆく' },
        { text: "月", link: '/ヰ世界情緒/月' },
        { text: "桜流し", link: '/ヰ世界情緒/桜流し' },
        { text: "死ぬのがいいわ", link: '/ヰ世界情緒/死ぬのがいいわ' },
        { text: "泡沫", link: '/ヰ世界情緒/泡沫' },
        { text: "海の幽霊", link: '/ヰ世界情緒/海の幽霊' },
        { text: "熱愛発覚中", link: '/ヰ世界情緒/熱愛発覚中' },
        { text: "熱異常", link: '/ヰ世界情緒/熱異常' },
        { text: "猫の食卓", link: '/ヰ世界情緒/猫の食卓' },
        { text: "異星にいこうね", link: '/ヰ世界情緒/異星にいこうね' },
        { text: "白昼夢", link: '/ヰ世界情緒/白昼夢' },
        { text: "第三の心臓", link: '/ヰ世界情緒/第三の心臓' },
        { text: "約束", link: '/ヰ世界情緒/約束' },
        { text: "誰か、海を。", link: '/ヰ世界情緒/誰か、海を。' },
        { text: "運命", link: '/ヰ世界情緒/運命' },
        { text: "霞がついてくる", link: '/ヰ世界情緒/霞がついてくる' },
        { text: "鳳仙花", link: '/ヰ世界情緒/鳳仙花' },      ],
      },
      { text: '明透', collapsed: false, items: [
        { text: "CH4NGE", link: '/明透/CH4NGE' },
        { text: "NIGHT DANCER", link: '/明透/NIGHT DANCER' },
        { text: "Overdose", link: '/明透/Overdose' },
        { text: "ねむるまち feat. yama", link: '/明透/ねむるまち feat. yama' },
        { text: "アンダーブーケ", link: '/明透/アンダーブーケ' },
        { text: "インパーフェクト", link: '/明透/インパーフェクト' },
        { text: "カワキヲアメク", link: '/明透/カワキヲアメク' },
        { text: "シンデレラボーイ", link: '/明透/シンデレラボーイ' },
        { text: "スロウリー", link: '/明透/スロウリー' },
        { text: "ソラゴト", link: '/明透/ソラゴト' },
        { text: "デスペレート feat. LOLUET", link: '/明透/デスペレート feat. LOLUET' },
        { text: "フラジール", link: '/明透/フラジール' },
        { text: "マシュマリー", link: '/明透/マシュマリー' },
        { text: "ライトイヤーズ", link: '/明透/ライトイヤーズ' },
        { text: "唱", link: '/明透/唱' },
        { text: "帝国少女", link: '/明透/帝国少女' },
        { text: "徒花の涙", link: '/明透/徒花の涙' },
        { text: "新時代 (ウタ from ONE PIECE FILM RED)", link: '/明透/新時代 (ウタ from ONE PIECE FILM RED)' },
        { text: "秒針を噛む", link: '/明透/秒針を噛む' },
        { text: "第六感", link: '/明透/第六感' },
        { text: "虎視眈々", link: '/明透/虎視眈々' },      ],
      },
      { text: '星街すいせい', collapsed: false, items: [
        { text: "ビビデバ", link: '/星街すいせい/ビビデバ' },      ],
      },
      { text: '理芽', collapsed: false, items: [
        { text: "Flowering (with Misumi)", link: '/理芽/Flowering (with Misumi)' },
        { text: "NEUROMANCE", link: '/理芽/NEUROMANCE' },
        { text: "いたいよ", link: '/理芽/いたいよ' },
        { text: "おしえてかみさま", link: '/理芽/おしえてかみさま' },
        { text: "さみしいひと", link: '/理芽/さみしいひと' },
        { text: "どくどく", link: '/理芽/どくどく' },
        { text: "インナアチャイルド", link: '/理芽/インナアチャイルド' },
        { text: "クライベイビー", link: '/理芽/クライベイビー' },
        { text: "チクタクボーイ", link: '/理芽/チクタクボーイ' },
        { text: "デイネイ", link: '/理芽/デイネイ' },
        { text: "ピルグリム", link: '/理芽/ピルグリム' },
        { text: "ピロウトーク", link: '/理芽/ピロウトーク' },
        { text: "ファンファーレ", link: '/理芽/ファンファーレ' },
        { text: "フロム天国 feat. EMA", link: '/理芽/フロム天国 feat. EMA' },
        { text: "ルフラン feat. 笹川真生", link: '/理芽/ルフラン feat. 笹川真生' },
        { text: "傷は増え続ける、だけどそれでいい", link: '/理芽/傷は増え続ける、だけどそれでいい' },
        { text: "十九月", link: '/理芽/十九月' },
        { text: "宿木", link: '/理芽/宿木' },
        { text: "想像して、創造して", link: '/理芽/想像して、創造して' },
        { text: "法螺話 (with Guiano)", link: '/理芽/法螺話 (with Guiano)' },
        { text: "狂えない", link: '/理芽/狂えない' },
        { text: "甘美な無法", link: '/理芽/甘美な無法' },
        { text: "生きているより楽しそう", link: '/理芽/生きているより楽しそう' },
        { text: "百年", link: '/理芽/百年' },
        { text: "私的", link: '/理芽/私的' },
        { text: "空っぽなら、踊ろうぜ", link: '/理芽/空っぽなら、踊ろうぜ' },
        { text: "素的", link: '/理芽/素的' },
        { text: "絵画のように美しくいたかった", link: '/理芽/絵画のように美しくいたかった' },
        { text: "言っちゃいけないことばっか浮かぶよな", link: '/理芽/言っちゃいけないことばっか浮かぶよな' },
        { text: "詞を書く化物", link: '/理芽/詞を書く化物' },
        { text: "食虫植物", link: '/理芽/食虫植物' },
        { text: "魔的 feat. 花譜", link: '/理芽/魔的 feat. 花譜' },      ],
      },
      { text: '花譜', collapsed: false, items: [
        { text: "Beyond META", link: '/花譜/Beyond META' },
        { text: "CAN-VERSE", link: '/花譜/CAN-VERSE' },
        { text: "Re", link: '/花譜/Re' },
        { text: "Re:HEROINES", link: '/花譜/Re:HEROINES' },
        { text: "quiz", link: '/花譜/quiz' },
        { text: "あさひ", link: '/花譜/あさひ' },
        { text: "あの夏が飽和する feat. 花譜", link: '/花譜/あの夏が飽和する feat. 花譜' },
        { text: "あるふぁYOU", link: '/花譜/あるふぁYOU' },
        { text: "そして花になる", link: '/花譜/そして花になる' },
        { text: "それを世界と言うんだね", link: '/花譜/それを世界と言うんだね' },
        { text: "まほう feat. 理芽", link: '/花譜/まほう feat. 理芽' },
        { text: "わたしの声", link: '/花譜/わたしの声' },
        { text: "わたしの線香", link: '/花譜/わたしの線香' },
        { text: "アンサー", link: '/花譜/アンサー' },
        { text: "イマジナリーフレンド", link: '/花譜/イマジナリーフレンド' },
        { text: "エリカ", link: '/花譜/エリカ' },
        { text: "トウキョウ・シャンディ・ランデヴ feat. 花譜,ツミキ", link: '/花譜/トウキョウ・シャンディ・ランデヴ feat. 花譜,ツミキ' },
        { text: "ニヒル", link: '/花譜/ニヒル' },
        { text: "メルの黄昏", link: '/花譜/メルの黄昏' },
        { text: "モンタージュ", link: '/花譜/モンタージュ' },
        { text: "ラブしい", link: '/花譜/ラブしい' },
        { text: "不可解", link: '/花譜/不可解' },
        { text: "不埒な喝采", link: '/花譜/不埒な喝采' },
        { text: "世惑い子", link: '/花譜/世惑い子' },
        { text: "人を気取る", link: '/花譜/人を気取る' },
        { text: "例えば", link: '/花譜/例えば' },
        { text: "危ノーマル", link: '/花譜/危ノーマル' },
        { text: "夜が降り止む前に", link: '/花譜/夜が降り止む前に' },
        { text: "夜行バスにて", link: '/花譜/夜行バスにて' },
        { text: "帰り路", link: '/花譜/帰り路' },
        { text: "彷徨い", link: '/花譜/彷徨い' },
        { text: "心臓と絡繰", link: '/花譜/心臓と絡繰' },
        { text: "忘れてしまえ", link: '/花譜/忘れてしまえ' },
        { text: "戸惑いテレパシー", link: '/花譜/戸惑いテレパシー' },
        { text: "春を発つ", link: '/花譜/春を発つ' },
        { text: "春陽", link: '/花譜/春陽' },
        { text: "景色", link: '/花譜/景色' },
        { text: "暗闇", link: '/花譜/暗闇' },
        { text: "未確認少女進行形", link: '/花譜/未確認少女進行形' },
        { text: "未観測", link: '/花譜/未観測' },
        { text: "流線形メーデー", link: '/花譜/流線形メーデー' },
        { text: "海に化ける", link: '/花譜/海に化ける' },
        { text: "深淵 feat. ヰ世界情緒", link: '/花譜/深淵 feat. ヰ世界情緒' },
        { text: "狂感覚", link: '/花譜/狂感覚' },
        { text: "畢生よ", link: '/花譜/畢生よ' },
        { text: "痛みを", link: '/花譜/痛みを' },
        { text: "神聖革命バーチャルリアリティ", link: '/花譜/神聖革命バーチャルリアリティ' },
        { text: "私論理", link: '/花譜/私論理' },
        { text: "秘密の言葉", link: '/花譜/秘密の言葉' },
        { text: "糸", link: '/花譜/糸' },
        { text: "花女", link: '/花譜/花女' },
        { text: "蕾に雷", link: '/花譜/蕾に雷' },
        { text: "裏表ガール", link: '/花譜/裏表ガール' },
        { text: "過去を喰らう", link: '/花譜/過去を喰らう' },
        { text: "邂逅", link: '/花譜/邂逅' },
        { text: "鏡よ鏡", link: '/花譜/鏡よ鏡' },
        { text: "雛鳥", link: '/花譜/雛鳥' },
        { text: "青春の温度", link: '/花譜/青春の温度' },
        { text: "魔女", link: '/花譜/魔女' },      ],
      },

  ],
    socialLinks: [
      { icon: 'twitter', link: 'https://github.com/vuejs/vitepress' },
    ],
    search: {
      provider: 'local',
    },
  },
})
